name: second_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  shared_preferences: ^2.3.3
  svg_image: ^0.0.5
  pinput: ^5.0.0
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  fluttertoast: ^8.2.10
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  dots_indicator: ^3.0.0
  animations: ^2.0.11
  http: ^1.2.2
  font_awesome_flutter: ^10.8.0
  uuid: ^4.5.1
  app_settings: ^5.1.1
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.9.0
  firebase_messaging: ^15.2.0
  image_picker: ^1.1.2
  geocoding: ^3.0.0
  loading_animation_widget: ^1.3.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.1
  webview_flutter_wkwebview: ^3.17.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translation/
    - images/MainLogo.png
    - images/error-warning-fill.png
    - images/Location 2.png
    - images/Location.png
    - images/Logo Small.svg
    - images/Logo.svg
    - images/Outlined.png
    - images/Profile.png
    - images/Saudi Flag.png
    - images/Search.png
    - images/Unlock.png
    - images/wave (3) 1 1.png
    - images/Mark.png
    - images/Arrow---Left.png
    - images/wave (3) 1 2.png
    - images/Photo.png
    - images/Location 1.png
    - images/Wallet 1.png
    - images/Package.png
    - images/Notification.png
    - images/Call.png
    - images/Language.png
    - images/Logout 1.png
    - images/Camera.png
    - images/About us.png
    - images/About us (1).png
    - images/Unlock 2.png
    - images/Privacy Policy.png
    - images/FAQs.png
    - images/Rectangle 44.png
    - images/Rectangle 101.png
    - images/Unlock 2 (1).png
    - images/Unlock 3.png
    - images/Unlock 4.png
    - images/X.png
    - images/FB.png
    - images/Outlined2.png
    - images/Outlined3.png
    - images/Arrow - Left 2.png
    - images/up.png
    - images/down.png
    - images/Unlock 22 (1).png
    - images/deleeete.png
    - images/User23.png
    - images/Logo Status (1).png
    - images/Home.png
    - images/Tag.png
    - images/Open Map Button.png
    - images/Logo Status (2).png
    - images/Location 122.png
    - images/Cars Size.png
    - images/Star 1.png
    - images/Check Box.png
    - images/Hint.png
    - images/Filter.png
    - images/Rial.png
    - images/Warning.png
    - images/Rectangle 100.png
    - images/Rectangle 444.png
    - images/Gift.png
    - images/BigRight.png
    - images/SmallPhoto.png
    - images/Present Another Shape.png
    - images/notificatiooons.png
    - images/halfCar.png
    - images/Asset 1 1.png
    - images/Asset 3 1.png
    - images/Home (1).png
    - images/Time Circle.png
    - images/car Wash.png
    - images/Outlined33.png
    - images/Sucess.png
    - images/Upload Photo.png
    - images/bi_cash.png
    - images/Thank you (1).png
    - images/Group.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
