// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC2A49YoSK_Vp8tn1Egqfm7QS-IDZcoOo',
    appId: '1:658060318403:web:fbda5f7b4bc7a12d417476',
    messagingSenderId: '658060318403',
    projectId: 'project-f0d26',
    authDomain: 'project-f0d26.firebaseapp.com',
    storageBucket: 'project-f0d26.firebasestorage.app',
    measurementId: 'G-9GF89N2WB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAINAmRvdEW52JgVPWEaWpYuKmVtQfTE3I',
    appId: '1:658060318403:android:70f988491cc5c37f417476',
    messagingSenderId: '658060318403',
    projectId: 'project-f0d26',
    storageBucket: 'project-f0d26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEDqBvXhKK8W_kNws4h41yLSJDvEsCMkA',
    appId: '1:658060318403:ios:f0715f87dc9a6a13417476',
    messagingSenderId: '658060318403',
    projectId: 'project-f0d26',
    storageBucket: 'project-f0d26.firebasestorage.app',
    iosBundleId: 'com.example.secondProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEDqBvXhKK8W_kNws4h41yLSJDvEsCMkA',
    appId: '1:658060318403:ios:f0715f87dc9a6a13417476',
    messagingSenderId: '658060318403',
    projectId: 'project-f0d26',
    storageBucket: 'project-f0d26.firebasestorage.app',
    iosBundleId: 'com.example.secondProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA21nquvU2mMvjM3diu9WTXOtlCMHBMCks',
    appId: '1:658060318403:web:70cd3651d617eb41417476',
    messagingSenderId: '658060318403',
    projectId: 'project-f0d26',
    authDomain: 'project-f0d26.firebaseapp.com',
    storageBucket: 'project-f0d26.firebasestorage.app',
    measurementId: 'G-83E1Q3C6RW',
  );
}
